CREATE TABLE tbl_secciones (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  seccion varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  visible int(11) NOT NULL,
  paginaPadre varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  titulo varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NULL,
  subTitulo varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NULL,
  texto varchar(10000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

INSERT INTO tbl_secciones (seccion, visible, paginaPadre, titulo, subTitulo, texto) VALUES
('hero', 1, 'home', 'Innovación y Soluciones Tecnológicas con <strong>UNICAB Solutions</strong>', '', 'En <strong>UNICAB Solutions</strong> transformamos ideas en soluciones tecnológicas que marcan la diferencia. Desde plataformas educativas personalizadas hasta software a medida y programas de capacitación en transformación digital, estamos aquí para revolucionar la forma en que aprendes, trabajas y lideras.<br><br>Nuestros servicios combinan innovación, personalización y tecnología avanzada para que alcances tus metas, sin importar el tamaño de tu proyecto o tu sector.'),
('servicios', 1, 'home', '', ' ', ''),
('disenoSistemas', 1, 'solutions', '', ' ', '<p class="texto-base descripcion-servicio"><span>Desarrollo de plataformas educativas LMS </span>personalizadas, desarrollo de plataformas de contenidos académicos interactivos y gamificados según necesidades y modelo pedagógico, aplicaciones móviles para la educación formal e informal.</p><ul class="ul-solutions"><li> <p class="texto-base descripcion-servicio"> <span>Diseño de plataformas educativas virtuales personalizadas (LMS):</span> Sistemas intuitivos y escalables que facilitan la enseñanza y el aprendizaje online.</p></li><li><p class="texto-base descripcion-servicio"><span>Elaboración de materiales educativos digitales:</span> Contenidos interactivos y multimedia diseñados con metodologías pedagógicas modernas y personalizados.</p></li><li><p class="texto-base descripcion-servicio"><span>Capacitación para docentes y estudiantes:</span> Formación en el uso de herramientas tecnológicas aplicadas a educación.</p></li></ul>'),
('desarrolloSoftware', 1, 'solutions', '', ' ', '<ul class="ul-solutions"><li><p class="texto-base descripcion-servicio"><span>Programas para empresas:</span> Diseñamos herramientas que ayudan a organizar mejor las actividades de un negocio, llevar inventarios, gestionar ventas o coordinar proyectos.</p></li><li><p class="texto-base descripcion-servicio"><span>Soluciones a la medida:</span> Si tienes una idea o necesidad específica, creamos un software personalizado para resolverla, ya sea en educación, producción, comercialización, logística, gerencia o cualquier área. </p> </li> <li> <p class="texto-base descripcion-servicio"> <span>Tecnología moderna:</span> Usamos lo mejor en tecnología para que el software sea rápido, eficiente y fácil de usar. </p> </li> <li> <p class="texto-base descripcion-servicio"> <span>Desarrollo desde cero:</span> Hacemos programas únicos, diseñados exclusivamente para ti, asegurando que cumplan exactamente con lo que buscas y en código puro. </p> </li> </ul>'),
('transformacionDigital', 1, 'solutions', '', ' ', '<ul class="ul-solutions"><li><p class="texto-base descripcion-servicio">Formación en el uso e implementación de <span>herramientas digitales avanzadas para potenciar procesos de enseñanza-aprendizaje</span> en instituciones educativas y empresas productivas. </p></li><li><p class="texto-base descripcion-servicio"><span>Talleres prácticos y personalizados para la adopción efectiva tecnologías emergentes, </span> diseñados según las necesidades específicas de cada organización. </p></li><li><p class="texto-base descripcion-servicio">Programas de <span>capacitación en competencias digitales, </span> enfocados en empoderar a docentes, estudiantes y empleados para enfrentar los retos del entorno digital actual. </p></li></ul>'),
('capacitacion', 1, 'solutions', '', ' ', '<ul class="ul-solutions"><li><p class="texto-base descripcion-servicio"><span>Capacitación en manejo de herramientas digitales para enseñanza aprendizaje para docentes</span> a través de cursos, diplomados y seminarios prácticos ajustados a las necesidades propias del grupo. </p></li><li><p class="texto-base descripcion-servicio"><span>Formación y transformación de liderazgo digital para implementar procesos de cambio digital en los trabajadores</span> y asumir el crecimiento de sus organizaciones. </p></li></ul>');



