DROP TABLE tbl_textos;

CREATE TABLE tbl_textos (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_seccion int(11) UNSIGNED NOT NULL,
  paginaPadre varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  identificacion varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NULL,
  texto mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  INDEX fk_tbl_textos_tbl_secciones (id_seccion),
  CONSTRAINT fk_tbl_textos_tbl_secciones FOREIGN KEY (id_seccion) REFERENCES tbl_secciones (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

INSERT INTO tbl_textos (id_seccion, paginaPadre, identificacion, texto ) VALUES 
(0, 'historia', 'fundacion', 'UNICAB Corporación Educativa fue creada en la ciudad de Sogamoso mediante la Resolución No. 0194 del 18 de julio de 2001, emitida por la Gobernación de Boyacá. Desde su inicio, se estableció como una institución sin ánimo de lucro, con una filosofía de vida orientada a ofrecer el derecho-servicio educativo de manera innovadora y acorde a las necesidades de quienes participan en sus procesos, fomentando el intercambio de saberes y fortaleciendo el liderazgo de sus participantes.<br>Desde su creación y hasta el año 2007, UNICAB Corporación Educativa desarrolló diversos servicios:' ),
(0, 'historia', 'giu', 'Es un cuerpo colegiado de investigación conformado por un grupo de maestros y asesores externos, cuyo objetivo es adelantar desarrollos científicos, tecnológicos, pedagógicos y estrategias complementarias del modelo pedagógico UNICAB Ecosistema. Este grupo gestiona proyectos y propuestas de investigación coherentes, orientados a consolidar componentes cognitivos, propedéuticos, estratégicos, metodológicos y sinérgicos para desarrollar contenidos, secuencias y métodos de aprendizaje. Todo esto se aplica en la educación virtual de forma disruptiva e innovadora dentro de un entorno cibernético, formulando y respondiendo con rigor investigativo a uno o varios problemas del entorno. Además, proporciona soluciones y medidas correctivas mediante planes estratégicos de mediano y largo plazo, con el fin de generar conocimientos concretos sobre las temáticas abordadas.' );

INSERT INTO tbl_textos (id_seccion, paginaPadre, identificacion, texto ) VALUES 
(13, 'principiosYValores', 'Compromiso', 'El colegio está comprometido en desarrollar a través de la mejora continua y el esfuerzo de un equipo de trabajadores que estudian, investigan, atienden y prestan los mejores servicios educativos a la comunidad, que garantizan la calidad y la excelencia de los aprendizajes en los proyectos de vida de estudiantes que han descubierto habilidades y destrezas, y que las potencializan con autonomía, libertad e identidad motivados por el deseo de cumplir con sus expectativas, el logro de las metas y objetivos de la institución, para que transformen con libertad una verdadera educación que desarrolle su personalidad autónomamente, apropiando el conocimiento en su vida práctica como lo planteaba John Dewey y como resultado el beneficio individual, familiar y comunitario.' ),
(13, 'principiosYValores', 'Honestidad', 'Actuar bajo la normatividad vigente con responsabilidad y ética en todos los aspectos relacionados con el desarrollo e interacción de las actividades de la institución con la sociedad. Ser transparentes en todo, y asegurar que cada una de las políticas adoptadas dentro del colegio, así como los compromisos adquiridos, sean sustentados a través de procesos definidos, integrados y ejecutados en las formas mismas que los estándares de calidad propuestos, a través de una estructura definida del quehacer institucional y su impacto en la sociedad.' ),
(13, 'principiosYValores', 'Libertad', 'Es la respuesta al silogismo ideológico de lo que se espera con respecto a lo que se es, nuestros estudiantes surten un proceso de acompañamiento que les permite identificarse y auto definirse para ser libres, para que empoderados se sientan eficientes a la hora de tomar decisiones; por lo que buscamos y privilegiamos siempre la verdad sin restricciones, para producir el conocimiento y el progreso de la sociedad con conciencia sobre sus intereses, derechos, deberes y responsabilidades políticas con un alto sentido de responsabilidad colectiva.' ),
(13, 'principiosYValores', 'Equidad', 'La dimensión pedagógica de la equidad en educación, fundamenta su escala estratégica para hacer frente a las desigualdades que subsisten pese a las políticas de ampliación de oportunidades registradas a escala mundial. Sustentamos un concepto de equidad integral, que recoge los postulados y fines propios de la educación en Colombia, con el de inclusión social para la participación y el empoderamiento, con asentamiento en las pedagogías críticas, de la capacidad y la educación centrada en el estudiante, que engloba procesos educativos inclusivos y dialógicos para fortalecer la agencia de los estudiantes no tradicionales en un modelo pedagógico virtual, tanto para aprender como para revertir las exclusiones educativas y sociales acumuladas. Esta dimensión es clave para optimizar las estrategias de ampliación de accesibilidad y cobertura que tan ardua alusión hace la ley general de educación frente a los fracasos que experimenta el estudiantado tradicional. Ello se evidencia en el análisis de prácticas innovadoras presenta este proyecto educativo.' ),
(13, 'principiosYValores', 'Responsabilidad', 'Surge como la alternativa para suplir una necesidad a los intereses de aquellos que siendo diferentes solicitan ser acogidos y acompañados en sus procesos y actividades extracurriculares en las artes, el deporte, la ciencia, la tecnología, y la investigación que desarrolla el mundo contemporáneo, en el que curiosa y comprometidamente quieren desenvolverse, pero que por convencionalismos formativos no se les permite espacios para cumplir sueños e inquietudes que los hacen diferentes. UNICAB encuentra ese esquema y se une al deseo de aquellos que por su proyecto de vida quieren transcender a otros escenarios, acompañados por un equipo de maestros comprometidos que orientan los procesos enseñanza aprendizaje con sensibilidad y consciencia y los tornan flexibles a través de la virtualidad humanizando el proceso, a través de un modelo pedagógico eco sistémico e investigativo.' );