DROP TABLE IF EXISTS tbl_sentencias;

CREATE TABLE tbl_sentencias (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  campos varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  tablas varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  condiciones varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  agrupaciones varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  ordenamientos varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  modificaciones varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  condicionesAgrupaciones varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

INSERT INTO tbl_sentencias (campos, tablas, condiciones, agrupaciones, ordenamientos, modificaciones, condicionesAgrupaciones) VALUES
('SELECT * ', 'FROM tbl_menus ', 'WHERE nivel = |x| AND padre = |y| AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_banners ', 'WHERE visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 1 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 2 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 3 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 4 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 5 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 6 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 7 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 8 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 9 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 10 AND visible = 1 ', '', '', '', ''),

('SELECT * ', 'FROM tbl_parametros ', 'WHERE parametro = |telefono_admisiones| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_parametros ', 'WHERE parametro = |correo_admisiones| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_parametros ', 'WHERE parametro = |direccion_unicab| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_parametros ', 'WHERE parametro = |ubicacion_unicab| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 2 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 3 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 4 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 5 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 6 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 7 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 8 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 9 ', '', '', '', ''),

('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 10 AND id < 39 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 11 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_menus ', 'WHERE visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_blogs ', 'WHERE id > 0 ', '', 'ORDER BY id DESC LIMIT 3 ', '', ''),
('SELECT * ', 'FROM tbl_parametros ', 'WHERE id_seccion = 8 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_formularios ', 'WHERE id_seccion = 4 ', '', '', '', ''),
('INSERT ', 'INTO tbl_contactos ', '(nombre, correo, asunto, mensaje, fecha) VALUES (?, ?, ?, ?, ?) ', '', '', '', ''),
('SELECT * ', 'FROM tbl_parametros ', 'WHERE id_seccion = 4 OR id IN (1, 2) ', '', '', '', ''),

('SELECT * ', 'FROM tbl_menus_solutions ', 'WHERE nivel = |x| AND padre = |y| AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 11 ', '', '', '', ''),

('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 10 AND descripcion = |logo| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_menus ', 'WHERE visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 10 AND descripcion = |social-media| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_parametros ', 'WHERE id >= 8 AND id < 12 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_parametros ', 'WHERE id >= 12 AND id <= 13 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 12 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 13 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 14 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 15 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 16 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 12 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 13 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 14 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 15 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 16 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 10 AND descripcion = |entidades| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 16 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 16 AND descripcion = |icon-search| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 16 AND descripcion = |image-contact| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 16 AND descripcion = |table-icon| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 16 AND descripcion = |image-schedule| ', '', '', '', ''),

('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 17 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 18 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 19 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 20 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 17 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 17 AND titulo=|search| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 17 AND descripcion=|table| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 18 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 19 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 20 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_eventos ', 'WHERE estado = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_archivos ', 'WHERE visible = 1 ', '', '', '', ''),

('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 21 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 22 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 23 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 24 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 21 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_textos ', 'WHERE id_seccion = 21 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 22  AND textoAlterno = |parteArriba| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 22  AND textoAlterno = |parteAbajo| ', '', 'ORDER BY id DESC LIMIT 1 ', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 23 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_textos ', 'WHERE id_seccion = 23 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 24 ', '', '', '', ''),

('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 25 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 26 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 26 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_opciones_estados_financieros ', 'WHERE nombrePadre = |Relación con la institución| ', '','','',''),
('SELECT * ', 'FROM tbl_opciones_estados_financieros ', 'WHERE nombrePadre = |Tipo de certificación| ', '','','',''),

('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 27 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 27 ', '', '', '', '');

('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 28 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 28 ', '', '', '', ''),

('SELECT * ', 'FROM tbl_publicaciones_academicas ', 'WHERE visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 29 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 29 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_textos ', 'WHERE id_seccion = 29 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_textos ', 'WHERE id_seccion = 30 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 30 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 30 ', '', '', '', ''),

('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 31 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 31 AND titulo = |Principal| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_textos ', 'WHERE id_seccion = 31 AND identificacion = |barraBusqueda| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_textos ', 'WHERE id_seccion = 31 AND identificacion = |linkBusqueda| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 32 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_blogs ', 'WHERE id > 0 ', '', 'ORDER BY id DESC LIMIT 4 ', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 33 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_blogs ', 'WHERE id > 0 ', '', 'ORDER BY id DESC LIMIT 1 ', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 33 ', '', '', '', '');
