DROP TABLE tbl_textos;

CREATE TABLE tbl_textos (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_seccion int(11) UNSIGNED NOT NULL,
  paginaPadre varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  identificacion varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NULL,
  texto mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  INDEX fk_tbl_textos_tbl_secciones (id_seccion),
  CONSTRAINT fk_tbl_textos_tbl_secciones FOREIGN KEY (id_seccion) REFERENCES tbl_secciones (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

INSERT INTO tbl_textos (id_seccion, paginaPadre, identificacion, texto ) VALUES 
(21, 'historia', 'Fundación', 'UNICAB Corporación Educativa fue creada en la ciudad de Sogamoso mediante la Resolución No. 0194 del 18 de julio de 2001, emitida por la Gobernación de Boyacá. Desde su inicio, se estableció como una institución sin ánimo de lucro, con una filosofía de vida orientada a ofrecer el derecho-servicio educativo de manera innovadora y acorde a las necesidades de quienes participan en sus procesos, fomentando el intercambio de saberes y fortaleciendo el liderazgo de sus participantes. <br> <br> Desde su creación y hasta el año 2007, UNICAB Corporación Educativa desarrolló diversos servicios:' ),
(21, 'historia', '2002-2003', '<b>Con la Cámara de Comercio de Sogamoso:</b> Se llevaron a cabo procesos de formación, capacitación y empoderamiento de comerciantes en Sogamoso y en ocho municipios de la Provincia de Sugamuxi, a través de estrategias enfocadas en mercadeo, ventas y atención al cliente, entre otros. <br> <br> <b>Proyecto “Recuperación del Tejido Social de la Cadena Productiva del Carbón del Altiplano Cundiboyacense”:</b> Este proyecto, liderado por el Programa de las Naciones Unidas para el Desarrollo (PNUD), se implementó en 13 municipios productores de carbón en Boyacá. Se realizaron procesos de formación, sensibilización, concientización y capacitación dirigidos a trabajadores mineros, sus familias y comunidades.' ),
(21, 'historia', '2004-2007', '<b>Con el Instituto Colombiano de Bienestar Familiar (ICBF) y municipios de las provincias de Sugamuxi y Tundama:</b> En Sugamuxi: Sogamoso, Duitama, Paipa, Iza, Monguí, Gámeza, Mongua, Aquitania, Tota, Cuítiva, Corrales. En Tundama: Paipa, Duitama, Sogamoso, Corrales, Nobsa. Se desarrolló el <b>programa El Educador Familiar.</b> <br> <br> <b>Programa Atención a Población Rural Dispersa y El Educador Familiar:</b> Cofinanciado por el ICBF y 10 municipios de las provincias de Tundama y Sugamuxi, este programa atendió a comunidades rurales y poblaciones con necesidades educativas específicas. <br> <br> En 2007, surgió la necesidad de atender a personas con condiciones socioeconómicas especiales, como deportistas de alto rendimiento, artistas, familias en constante movilidad global, y campesinos que no podían acceder a la educación presencial.' ),
(21, 'historia', '2007-2008', 'Para responder a esta necesidad, se solicitó a la Secretaría de Educación de Sogamoso una licencia de funcionamiento provisional para prestar servicios educativos mediante TIC. Así nació el <b>proyecto del Colegio Virtual UNICAB </b>(www.unicab.org), autorizado por la Resolución No. 061 del 15 de diciembre de 2007. <br> <br> Desde 2008 hasta la fecha, el Colegio Virtual UNICAB ha graduado a 655 estudiantes de grado 11 y ha atendido a más de 5,000 estudiantes entre deportistas, artistas, niños, jóvenes y adultos. Este modelo ha permitido alcanzar resultados académicos sobresalientes, fomentando habilidades y motivando a los estudiantes a lograr sus metas. Muchos de ellos han obtenido becas en universidades nacionales e internacionales.' ),
(23, 'historia', 'giu', 'Es un cuerpo colegiado de investigación conformado por un grupo de maestros y asesores externos, cuyo objetivo es adelantar desarrollos científicos, tecnológicos, pedagógicos y estrategias complementarias del modelo pedagógico UNICAB Ecosistema. Este grupo gestiona proyectos y propuestas de investigación coherentes, orientados a consolidar componentes cognitivos, propedéuticos, estratégicos, metodológicos y sinérgicos para desarrollar contenidos, secuencias y métodos de aprendizaje. Todo esto se aplica en la educación virtual de forma disruptiva e innovadora dentro de un entorno cibernético, formulando y respondiendo con rigor investigativo a uno o varios problemas del entorno. Además, proporciona soluciones y medidas correctivas mediante planes estratégicos de mediano y largo plazo, con el fin de generar conocimientos concretos sobre las temáticas abordadas.' ),
(23, 'historia', 'creativo', 'Está conformado por un selecto grupo de docentes de la institución y asesores externos, quienes, de manera libre y voluntaria, aportan su intelecto y creatividad en beneficio del desarrollo instruccional, visual, corporativo, pedagógico y publicitario. Este equipo se encarga de revisar y hacer seguimiento al material didáctico-pedagógico producido por los maestros mediadores antes de que sea publicado en las plataformas tecnológicas y canales de comunicación. También contribuye al apoyo en la gestión académica, las proyecciones empresariales, eventos interinstitucionales y trabajos publicitarios requeridos.' ),
(23, 'historia', 'sistemas', 'Está integrado por docentes de la institución, ingenieros de sistemas externos y partners, quienes, de manera libre y voluntaria, contribuyen al desarrollo holístico e informático. Este equipo organiza y mantiene funcionales los recursos de hardware necesarios para la ejecución del software, buscando siempre la mayor rapidez y calidad en el manejo de la información institucional. Coordina acciones con las diferentes dependencias y usuarios del sistema para garantizar una excelente calidad en los procesos informáticos del colegio. Además, realiza labores de actualización, soporte y mantenimiento técnico o tecnológico, siguiendo las normas y procedimientos vigentes. Proporciona soporte técnico en hardware y software, capacita a usuarios en la utilización de programas, instala y actualiza aplicativos necesarios para las plataformas y efectúa controles periódicos. Asimismo, apoya en la comprensión y manejo de las tecnologías implementadas, supervisando su aplicación y funcionamiento.' ),
(23, 'historia', 'corrección', 'Este equipo se encarga de revisar los contenidos generados por los maestros en la plataforma, asegurando la calidad y corrección de los mismos. Recibe acceso a los contenidos por parte del líder del pensamiento y brinda retroalimentación a través de informes que incluyen observaciones y sugerencias para mejoras. También revisa documentos antes de su publicación o envío mediante los diferentes medios de comunicación. Al igual que el equipo creativo, puede utilizar un formato tipo lista de chequeo para garantizar un análisis estructurado y eficiente.' ),
(23, 'historia', 'maestros', 'Este grupo está constituido por todo el personal docente con carga académica en el Colegio Virtual UNICAB, quienes además tienen asignada la dirección de grado. Este año se implementó un formato denominado Informe General de Dirección de Grado, que documenta tanto la carga académica como las actividades relacionadas con la dirección de grado. Aunque confiamos plenamente en la labor del personal, la experiencia ha demostrado la importancia de dejar evidencia para respaldar las acciones realizadas. <br><br> El grupo también evalúa el nivel de participación de los estudiantes en el pensamiento, describiendo el desempeño de cada uno con el propósito de establecer criterios objetivos de valoración. Esto permite aplicar estrategias preventivas, correctivas y productivas para mejorar el desempeño y garantizar la inclusión o promoción de los estudiantes.' );
