DROP TABLE tbl_sentencias;

CREATE TABLE tbl_sentencias (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  campos varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  tablas varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  condiciones varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  agrupaciones varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  ordenamientos varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  modificaciones varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  condicionesAgrupaciones varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

INSERT INTO tbl_sentencias (campos, tablas, condiciones, agrupaciones, ordenamientos, modificaciones, condicionesAgrupaciones) VALUES
('SELECT * ', 'FROM tbl_menus ', 'WHERE nivel = |x| AND padre = |y| AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_banners ', 'WHERE visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 1 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 2 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 3 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 4 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 5 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 6 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 7 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 8 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 9 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 10 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_parametros ', 'WHERE parametro = |telefono_admisiones| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_parametros ', 'WHERE parametro = |correo_admisiones| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_parametros ', 'WHERE parametro = |direccion_unicab| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_parametros ', 'WHERE parametro = |ubicacion_unicab| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 2 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 3 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 4 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 5 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 6 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 7 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 8 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 9 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 10 AND descripcion = |logo| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_menus ', 'WHERE visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 10 AND descripcion = |social-media| ', '', '', '', ''),
('SELECT * ', 'FROM tbl_parametros ', 'WHERE 5 <= id AND id < 9 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_parametros ', 'WHERE 9 <= id AND id < 11 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 11 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 12 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 13 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 14 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 15 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 11 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 12 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 13 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 14 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_secciones ', 'WHERE id = 15 AND visible = 1 ', '', '', '', ''),
('SELECT * ', 'FROM tbl_imagenes ', 'WHERE id_seccion = 10 AND descripcion = |entidades| ', '', '', '', '');